-- ============================================================
-- Migration : 9 fiches machines → machine_templates
-- Run each INSERT separately in Supabase SQL Editor
-- ============================================================

-- 1. Sertissage
INSERT INTO machine_templates ("machineKey","machineLabel",subtitle,sections,"createdAt","updatedAt")
VALUES ('sertissage','Machine de sertissage','Plan de maintenance preventive systematique','[{"key":"monthly","title":"Maintenance mensuelle","tasks":[{"number":1,"label":"Verifier le systeme de securite (Arret urgence, capot, marche-Arret)","criterion":"Marche et arret"},{"number":2,"label":"Verifier le manometre de pression et les pieces pneumatique","criterion":"En bonne etat"},{"number":3,"label":"Verifier l etat des machoires","criterion":"En bonne etat"},{"number":4,"label":"Verifier l etat des couteaux","criterion":"Pas d usure"},{"number":5,"label":"Verifier l etat des capteurs et leur bon fonctionnement","criterion":"En bonne etat"},{"number":6,"label":"Verifier l etat du module de denudage","criterion":"Bonne etat / propre"},{"number":7,"label":"Nettoyer l interieure de la machine avec un aspirateur","criterion":"Utiliser un aspirateur"},{"number":8,"label":"Verifier le poincons et les griffes de serrage de basse outil","criterion":"Usees"}]},{"key":"semiannual","title":"Maintenance semestrielle","tasks":[{"number":9,"label":"Verifier generale sur la machine","criterion":"Pas d endommagement"},{"number":10,"label":"Verifier les parametres","criterion":"OK"},{"number":11,"label":"Verifier l etat de moteur et leur systeme de refroidissement","criterion":"Pas de coincement"},{"number":12,"label":"Verifier la coffre electrique de la machine","criterion":"Pas d usure"},{"number":13,"label":"Nettoyer et graisser la cremaliere et les pignon du presse","criterion":"En bonne etat"}]}]',NOW(),NOW());

-- 2. Marquage
INSERT INTO machine_templates ("machineKey","machineLabel",subtitle,sections,"createdAt","updatedAt")
VALUES ('marquage','Machine de Marquage','Plan de maintenance preventive systematique','[{"key":"monthly","title":"Maintenance mensuelle","tasks":[{"number":1,"label":"Controler le niveau de la bouteille d encre","criterion":"OK"},{"number":2,"label":"Controler le niveau de la bouteille de solvant","criterion":"OK"},{"number":3,"label":"Nettoyer la tete d impression","criterion":"En bonne etat"},{"number":4,"label":"Verifier et nettoyer le bouchon de buse","criterion":"En bonne etat"},{"number":5,"label":"Nettoyer l ecran tactile","criterion":"En bonne etat"},{"number":6,"label":"Controler la natte filtrante - la nettoyer ou remplacer si necessaire","criterion":"En bonne etat"}]},{"key":"semiannual","title":"Maintenance semestrielle","tasks":[{"number":7,"label":"Vider le systeme d impression","criterion":"controle"},{"number":8,"label":"Changer kit filtres (filtre retour, filtre principal et filtre a air)","criterion":"controle / change"},{"number":9,"label":"Changer l encre","criterion":"controle / change"},{"number":10,"label":"Remplacer la bisette","criterion":"controle / change"},{"number":11,"label":"Evacuer les impuretes de l armoire de commande","criterion":"Propre"}]}]',NOW(),NOW());

-- 3. Ultrason
INSERT INTO machine_templates ("machineKey","machineLabel",subtitle,sections,"createdAt","updatedAt")
VALUES ('ultrason','Machine de ULTRASON','Plan de maintenance preventive systematique','[{"key":"monthly","title":"Maintenance mensuelle","tasks":[{"number":1,"label":"Controler les accessoires de securite (bouton urgence, Switch)","criterion":"OK"},{"number":2,"label":"Nettoyage generale de la machine (brins de cuivre et dechets)","criterion":"Propre"},{"number":3,"label":"Purger l unite d air et la nettoyer si presence d huile","criterion":"Propre"},{"number":4,"label":"Controler et nettoyer les filtres - verification bon fonctionnement ventilateur","criterion":"En bonne etat"},{"number":5,"label":"Verification l etat des pieces de soudage (enclume, plaquette, mors mobile, sonotrode)","criterion":"En bonne etat"},{"number":6,"label":"Verification du point zero de la machine (Calibrage)","criterion":"En bonne etat"}]},{"key":"semiannual","title":"Maintenance semestrielle","tasks":[{"number":7,"label":"Verifier le sonotrode et le couple de serrage (95N.m) avec l ecrou de positionnement","criterion":"controle"},{"number":8,"label":"Assurer le serrage du convertisseur (135N.m) et verification des elements fixes","criterion":"controle"},{"number":9,"label":"Graissage de coulisseau lateral","criterion":"controle / Lubrifier"},{"number":10,"label":"Graissage les roulements de guidage d enclume","criterion":"controle / Lubrifier"}]}]',NOW(),NOW());

-- 4. Vague
INSERT INTO machine_templates ("machineKey","machineLabel",subtitle,sections,"createdAt","updatedAt")
VALUES ('vague','Machine de Vague','Plan de maintenance preventive systematique','[{"key":"monthly","title":"Maintenance mensuelle","tasks":[{"number":1,"label":"Verifier le systeme de securite (Arret urgence, marche-Arret)","criterion":"OK"},{"number":2,"label":"Verifier l etat du resine","criterion":"OK"},{"number":3,"label":"Verifier la circuit d eau demineralise et le niveau du reservoir","criterion":"OK"},{"number":4,"label":"Verifier la circuit du vigon et le reservoir","criterion":"En bonne etat"},{"number":5,"label":"Nettoyage le filtre interieur","criterion":"En bonne etat"},{"number":6,"label":"Verifier les joints de la porte de fermeture","criterion":"En bonne etat"}]},{"key":"semiannual","title":"Maintenance semestrielle","tasks":[{"number":7,"label":"Verifier le ventilateur et la resistance de chauffage","criterion":"controle"},{"number":8,"label":"Controler le filtre de 5um et 10um","criterion":"controle / change"},{"number":9,"label":"Verifier les pompes et les electrovannes","criterion":"controle / change"},{"number":10,"label":"Controler la concentration du vigon","criterion":"controle / change"}]}]',NOW(),NOW());

-- 5. Bobinage
INSERT INTO machine_templates ("machineKey","machineLabel",subtitle,sections,"createdAt","updatedAt")
VALUES ('bobinage','Machine de Bobinage','Plan de maintenance preventive systematique','[{"key":"monthly","title":"Maintenance mensuelle","tasks":[{"number":1,"label":"Verifier le systeme de securite (capot de protection, bouton urgence)","criterion":"OK"},{"number":2,"label":"Verifier le more de fixation du bobine","criterion":"OK"},{"number":3,"label":"Verifier le mouvement de chariot et les butees","criterion":"En bonne etat"},{"number":4,"label":"Verifier les courroies","criterion":"En bonne etat"},{"number":5,"label":"Nettoyer l interieur de la machine","criterion":"En bonne etat"},{"number":6,"label":"Verifier les roues et le systeme mecanique","criterion":"En bonne etat"}]},{"key":"semiannual","title":"Maintenance semestrielle","tasks":[{"number":12,"label":"Verifier et controler l etat du roue et de vis sans fin","criterion":"controle"},{"number":13,"label":"Graissage et lubrification du roue et de vis sans fin","criterion":"Lubrifier"},{"number":14,"label":"Verifier l etat du ruban metallique","criterion":"controle / change"},{"number":15,"label":"Verifier le systeme magnetique du transport","criterion":"controle / change"},{"number":16,"label":"Verifier l etat des devdoires","criterion":"En bonne etat"}]}]',NOW(),NOW());

-- 6. Coupe
INSERT INTO machine_templates ("machineKey","machineLabel",subtitle,sections,"createdAt","updatedAt")
VALUES ('coupe','Machine de COUPE','Plan de maintenance preventive systematique','[{"key":"monthly","title":"Maintenance mensuelle","tasks":[{"number":1,"label":"Verifier le systeme de securite (Arret urgence, marche-Arret)","criterion":"OK"},{"number":2,"label":"Verifier l etat des filtres de ventilateurs","criterion":"OK"},{"number":3,"label":"Verification etat des courroies et des galets","criterion":"En bonne etat"},{"number":4,"label":"Calibrage, nettoyage tete de coupe et verifier l etat couteaux","criterion":"En bonne etat"},{"number":5,"label":"Verifier l etat de derouleur","criterion":"En bonne etat"},{"number":6,"label":"Verifier l etat de convoyeur","criterion":"En bonne etat"}]},{"key":"semiannual","title":"Maintenance semestrielle","tasks":[{"number":7,"label":"Verifier l etat des courroies, des moteurs de chaque unite et calibre","criterion":"controle / change"},{"number":8,"label":"Faire evacuer les impuretes de l armoire de commande","criterion":"controle"},{"number":9,"label":"Graissage des axes de mouvements","criterion":"graissage / controle"},{"number":10,"label":"Verifier absence de corrosion au niveau des pieces en mouvement","criterion":"controle"},{"number":11,"label":"Verifier l etat de derouleur (les verins et les capteurs)","criterion":"controle"},{"number":12,"label":"Verifier l etat de convoyeur (les verins et les capteurs)","criterion":"controle"},{"number":13,"label":"Verifier l etat de courroie du convoyeurs","criterion":"controle"}]}]',NOW(),NOW());

-- 7. Presse mecanique
INSERT INTO machine_templates ("machineKey","machineLabel",subtitle,sections,"createdAt","updatedAt")
VALUES ('presse-mecanique','Machine de Presse Mecanique','Plan de maintenance preventive systematique','[{"key":"monthly","title":"Maintenance mensuelle","tasks":[{"number":1,"label":"Verifier le systeme de securite de la machine","criterion":"OK"},{"number":2,"label":"Verifier la coffree et l installation electrique de la machine","criterion":"OK"},{"number":3,"label":"Verifier le systeme pneumatique de la machine","criterion":"En bonne etat"},{"number":4,"label":"Verifier les accessoires et les outils lie a la machine","criterion":"controle"}]},{"key":"semiannual","title":"Maintenance semestrielle","tasks":[{"number":7,"label":"Nettoyage generale de la machine","criterion":"En bonne etat"},{"number":8,"label":"Controle des verins et les distributeurs","criterion":"controle"},{"number":9,"label":"Lubrification et graissage de la machine et les outils","criterion":"graissage / controle"}]}]',NOW(),NOW());

-- 8. Soudure
INSERT INTO machine_templates ("machineKey","machineLabel",subtitle,sections,"createdAt","updatedAt")
VALUES ('soudure','Machine de Soudure','Plan de maintenance preventive systematique','[{"key":"monthly","title":"Maintenance mensuelle","tasks":[{"number":1,"label":"Verifier le systeme de securite (Arret urgence, marche-Arret)","criterion":"OK"},{"number":2,"label":"Nettoyage generale de la machine","criterion":"OK"},{"number":4,"label":"Verifier les electrodes du soudure","criterion":"En bonne etat"},{"number":5,"label":"Verifier les systeme de refroidissement","criterion":"En bonne etat"}]},{"key":"semiannual","title":"Maintenance semestrielle","tasks":[{"number":7,"label":"Changer si necessaire le reservoir et Verifier la circuit d eau","criterion":"controle / change"},{"number":8,"label":"Verification du sonde et de la pompe","criterion":"controle"},{"number":9,"label":"Verifier la circuit pneumatique","criterion":"controle"},{"number":10,"label":"Verifier la coffree et l installation electrique de la machine","criterion":"controle"}]}]',NOW(),NOW());

-- 9. Bouteuse
INSERT INTO machine_templates ("machineKey","machineLabel",subtitle,sections,"createdAt","updatedAt")
VALUES ('bouteuse','Machine de Bouteuse','Plan de maintenance preventive systematique','[{"key":"monthly","title":"Maintenance mensuelle","tasks":[{"number":1,"label":"Verifier le systeme de securite (capteur de presence, marche-Arret)","criterion":"OK"},{"number":2,"label":"Nettoyer l interieur de la machine avec l air comprime","criterion":"OK"},{"number":3,"label":"Verifier les lames de coupes et les ressort de serrages","criterion":"controle / change"}]},{"key":"semiannual","title":"Maintenance semestrielle","tasks":[{"number":7,"label":"Graissage du pignon de bec","criterion":"graissage"},{"number":8,"label":"Graissage l engrenage du reducteur","criterion":"graissage"},{"number":9,"label":"Huiler l axe du retenteur","criterion":"graissage / Huilee"},{"number":10,"label":"Huiler l axe du presse languette et la roulette","criterion":"graissage / Huilee"}]}]',NOW(),NOW());

-- Verify
SELECT "machineKey", "machineLabel" FROM machine_templates ORDER BY "createdAt";
